DUMMY_QPU_SPECS = {
    "name": "FRESNEL",
    "dimensions": 2,
    "rydberg_level": 60,
    "min_atom_distance": 5,
    "max_atom_num": 100,
    "max_radial_distance": 46,
    "interaction_coeff_xy": None,
    "supports_slm_mask": False,
    "min_layout_filling": 0.35,
    "max_layout_filling": 0.55,
    "optimal_layout_filling": 0.45,
    "min_layout_traps": 60,
    "max_layout_traps": 217,
    "max_sequence_duration": 6000,
    "max_runs": 1000,
    "reusable_channels": False,
    "default_noise_model": {
        "noise_types": ["SPAM", "dephasing", "relaxation"],
        "runs": None,
        "samples_per_run": None,
        "state_prep_error": 0.0,
        "p_false_pos": 0.025,
        "p_false_neg": 0.1,
        "temperature": 0.0,
        "laser_waist": None,
        "amp_sigma": 0.0,
        "relaxation_rate": 0.01,
        "dephasing_rate": 0.2222222222222222,
        "hyperfine_dephasing_rate": 0.0,
        "depolarizing_rate": 0.0,
        "eff_noise": [],
    },
    "pre_calibrated_layouts": [],
    "version": "1",
    "pulser_version": "1.5.4",
    "channels": [
        {
            "id": "rydberg_global",
            "basis": "ground-rydberg",
            "addressing": "Global",
            "max_abs_detuning": 62.83185307179586,
            "max_amp": 12.566370614359172,
            "min_retarget_interval": None,
            "fixed_retarget_t": None,
            "max_targets": None,
            "clock_period": 4,
            "min_duration": 16,
            "max_duration": 6000,
            "min_avg_amp": 0.3141592653589793,
            "mod_bandwidth": 5,
            "custom_phase_jump_time": 0,
            "eom_config": {
                "limiting_beam": "RED",
                "max_limiting_amp": 175.92918860102841,
                "intermediate_detuning": 2827.4333882308138,
                "controlled_beams": ["BLUE"],
                "mod_bandwidth": 26,
                "custom_buffer_time": 240,
                "multiple_beam_control": False,
                "red_shift_coeff": 2,
            },
            "propagation_dir": [0, 1, 0],
        }
    ],
    "is_virtual": False,
}
FAKE_RESULTS = str({"counters": {"0001": 1, "0010": 2, "0100": 3, "1000": 4}})
